# ruff: noqa: PGH004
# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import person_pb2 as person__pb2

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in person_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AddressBookServiceStub(object):
    """The AddressBook service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPerson = channel.unary_unary(
            "/person.AddressBookService/GetPerson",
            request_serializer=person__pb2.GetPersonRequest.SerializeToString,
            response_deserializer=person__pb2.GetPersonResponse.FromString,
            _registered_method=True,
        )
        self.ListPeople = channel.unary_unary(
            "/person.AddressBookService/ListPeople",
            request_serializer=person__pb2.ListPeopleRequest.SerializeToString,
            response_deserializer=person__pb2.ListPeopleResponse.FromString,
            _registered_method=True,
        )
        self.AddPerson = channel.unary_unary(
            "/person.AddressBookService/AddPerson",
            request_serializer=person__pb2.AddPersonRequest.SerializeToString,
            response_deserializer=person__pb2.AddPersonResponse.FromString,
            _registered_method=True,
        )


class AddressBookServiceServicer(object):
    """The AddressBook service definition"""

    def GetPerson(self, request, context):
        """Get a person by ID"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPeople(self, request, context):
        """List all people in the address book"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddPerson(self, request, context):
        """Add a new person to the address book"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AddressBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetPerson": grpc.unary_unary_rpc_method_handler(
            servicer.GetPerson,
            request_deserializer=person__pb2.GetPersonRequest.FromString,
            response_serializer=person__pb2.GetPersonResponse.SerializeToString,
        ),
        "ListPeople": grpc.unary_unary_rpc_method_handler(
            servicer.ListPeople,
            request_deserializer=person__pb2.ListPeopleRequest.FromString,
            response_serializer=person__pb2.ListPeopleResponse.SerializeToString,
        ),
        "AddPerson": grpc.unary_unary_rpc_method_handler(
            servicer.AddPerson,
            request_deserializer=person__pb2.AddPersonRequest.FromString,
            response_serializer=person__pb2.AddPersonResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "person.AddressBookService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "person.AddressBookService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AddressBookService(object):
    """The AddressBook service definition"""

    @staticmethod
    def GetPerson(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/person.AddressBookService/GetPerson",
            person__pb2.GetPersonRequest.SerializeToString,
            person__pb2.GetPersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPeople(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/person.AddressBookService/ListPeople",
            person__pb2.ListPeopleRequest.SerializeToString,
            person__pb2.ListPeopleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddPerson(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/person.AddressBookService/AddPerson",
            person__pb2.AddPersonRequest.SerializeToString,
            person__pb2.AddPersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
