# ruff: noqa: PGH004
# ruff: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto
# Protobuf Python Version: 6.31.1
"""
Generated protocol buffer code.

This file is auto-generated by the protocol buffer compiler, and should not be edited manually.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "person.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cperson.proto\x12\x07\x65xample"\xa1\x02\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12+\n\x06phones\x18\x04 \x03(\x0b\x32\x1b.example.Person.PhoneNumber\x1aW\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x38\n\x04type\x18\x02 \x01(\x0e\x32\x19.example.Person.PhoneType:\x0fPHONE_TYPE_HOME"h\n\tPhoneType\x12\x1a\n\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11PHONE_TYPE_MOBILE\x10\x01\x12\x13\n\x0fPHONE_TYPE_HOME\x10\x02\x12\x13\n\x0fPHONE_TYPE_WORK\x10\x03".\n\x0b\x41\x64\x64ressBook\x12\x1f\n\x06people\x18\x01 \x03(\x0b\x32\x0f.example.Personb\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "person_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PERSON"]._serialized_start = 26
    _globals["_PERSON"]._serialized_end = 315
    _globals["_PERSON_PHONENUMBER"]._serialized_start = 122
    _globals["_PERSON_PHONENUMBER"]._serialized_end = 209
    _globals["_PERSON_PHONETYPE"]._serialized_start = 211
    _globals["_PERSON_PHONETYPE"]._serialized_end = 315
    _globals["_ADDRESSBOOK"]._serialized_start = 317
    _globals["_ADDRESSBOOK"]._serialized_end = 363
# @@protoc_insertion_point(module_scope)
