[schema]
path = "taplo://taplo.toml"

[formatting]
align_entries         = true
indent_entries        = false
indent_tables         = true
reorder_arrays        = false
reorder_inline_tables = true
reorder_keys          = true
