---
line_ending: lf

formatter:
  include_document_start: true
  line_ending: lf
  retain_line_breaks_single: true
  max_line_length: 100
  drop_merge_tag: true
  pad_line_comments: 2
  trim_trailing_whitespace: true
  eof_newline: true
  force_array_style: block
