name: 🐛 Bug Report
description: Submit a bug report to help us improve
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        ## Please help us help you!

        Before filing your issue, ask yourself:

        - Has this bug already been reported?
        - Is this clearly a Pact Python bug?
        - Do I have basic ideas about where it goes wrong?
        - Could it be because of something on my end?

        **The GitHub issue tracker is not a support forum**. If you are not sure whether it could be on your end or within Pact Python, ask on [Slack](https://slack.pact.io).

        Make the bug obvious. Ideally, we should be able to understand it without running any code.

        Bugs are fixed faster if you include:
        - A reproduction repository to replicate the issue
        - Pact files
        - Logs

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label: I have read the [Contributing Guidelines on issues](https://github.com/pact-foundation/pact-python/main/CONTRIBUTING.md#issues).
          required: true

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please check the following items before creating a issue. This way we know you've done these steps first.
      options:
        - label: I'm using the latest version of `pact-python`.
          required: true
        - label: I have read the console error message carefully (if applicable).

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: input
    attributes:
      label: Reproducible demo
      description: |
        Paste the link to an example repo if possible, and exact instructions to reproduce the issue.

        > **What happens if you skip this step?** Someone will read your bug report, and maybe will be able to help you, but it's unlikely that it will get much attention from the team. Eventually, the issue will likely get closed in favor of issues that have reproducible demos.

        Please remember that:

        - Issues without reproducible demos have a very low priority.
        - The person fixing the bug would have to do that anyway. Please be respectful of their time.
        - You might figure out the issues yourself as you work on extracting it.

        Thanks for helping us help you!

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Write down the steps to reproduce the bug. You should start with a fresh installation, or your git repository linked above.
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. Step 3...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: How did you expect your project to behave? It's fine if you're not sure your understanding is correct. Write down what you thought would happen.
      placeholder: Write what you thought would happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        Did something go wrong? Is something broken, or not behaving as you expected? Describe this section in detail. Don't only say "it doesn't work"! Please submit exhaustive and complete log messages, not just the final error message.

        > Please read error messages carefully: it often tells you exactly what you are doing wrong.

        If the logs are too long, you can paste them in a [gist](https://gist.github.com/) and link it here.
      placeholder: |
        Write what happened. Add full console log messages.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Your environment
      description: Include as many relevant details about the environment you experienced the bug in.
      value: |
        - Public source code:
        - Is this a consumer or provider issue? Do you have information about the other side?
        - Pact Python version used: `pip list | grep pact`
        - Information about your Pact broker (version, hosted where, pactflow, ...)
        - Operating system and version (e.g. Ubuntu 20.04.2 LTS, macOS Ventura):

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.

        If you do check this box, please send a pull request. If circumstances change and you can't work on it anymore, let us know and we can re-assign it.
      options:
        - label: I'd be willing to fix this bug myself.
