# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import area_calculator_pb2 as area__calculator__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.calculateOne = channel.unary_unary(
                '/area_calculator.Calculator/calculateOne',
                request_serializer=area__calculator__pb2.ShapeMessage.SerializeToString,
                response_deserializer=area__calculator__pb2.AreaResponse.FromString,
                )
        self.calculateMulti = channel.unary_unary(
                '/area_calculator.Calculator/calculateMulti',
                request_serializer=area__calculator__pb2.AreaRequest.SerializeToString,
                response_deserializer=area__calculator__pb2.AreaResponse.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def calculateOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def calculateMulti(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'calculateOne': grpc.unary_unary_rpc_method_handler(
                    servicer.calculateOne,
                    request_deserializer=area__calculator__pb2.ShapeMessage.FromString,
                    response_serializer=area__calculator__pb2.AreaResponse.SerializeToString,
            ),
            'calculateMulti': grpc.unary_unary_rpc_method_handler(
                    servicer.calculateMulti,
                    request_deserializer=area__calculator__pb2.AreaRequest.FromString,
                    response_serializer=area__calculator__pb2.AreaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'area_calculator.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def calculateOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/area_calculator.Calculator/calculateOne',
            area__calculator__pb2.ShapeMessage.SerializeToString,
            area__calculator__pb2.AreaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def calculateMulti(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/area_calculator.Calculator/calculateMulti',
            area__calculator__pb2.AreaRequest.SerializeToString,
            area__calculator__pb2.AreaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
