extend = "../pyproject.toml"

[lint]
ignore = [
  "S101", # Forbid assert statements
  "D103", # Require docstring in public function
  "D104", # Require docstring in public package
]

[lint.per-file-ignores]
"tests/**.py" = [
  "INP001", # Forbid implicit namespaces
]
