#:schema https://json.schemastore.org/ruff.json
extend = "../pyproject.toml"

[lint.per-file-ignores]
"test_*.py" = [
  "D103",    # Require docstring in public function
  "D104",    # Require docstring in public package
  "INP001",  # Forbid implicit namespaces
  "PLR2004", # Forbid Magic Numbers
  "PLR2004", # Forbid magic values
  "S101",    # Forbid assert statements
  "TID252",  # Require absolute imports
]
