extend = "../pyproject.toml"

ignore = [
  "S101", # Forbid assert statements
  "D103", # Require docstring in public function
]

[per-file-ignores]
"tests/**.py" = [
  "INP001", # Forbid implicit namespaces
]
