"""
Provider contract tests using Pact (XML).

This module demonstrates how to test a FastAPI provider (see
[`provider.py`][examples.http.xml_example.provider]) against a mock consumer
using Pact. The mock consumer replays the requests defined by the consumer
contract, and Pact validates that the provider responds as expected.

Provider state handlers set up the in-memory database before each interaction
is verified, ensuring repeatable and isolated contract verification.
"""

from __future__ import annotations

import contextlib
import logging
import socket
import time
from threading import Thread
from typing import TYPE_CHECKING, Any, Literal

import pytest
import uvicorn

import pact._util
from examples.http.xml_example.provider import User, UserDb, app
from pact import Verifier

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


@pytest.fixture(scope="session")
def app_server() -> str:
    """
    Run the FastAPI server for provider verification.

    Returns:
        The base URL of the running FastAPI server.
    """
    hostname = "localhost"
    port = pact._util.find_free_port()  # noqa: SLF001
    Thread(
        target=uvicorn.run,
        args=(app,),
        kwargs={"host": hostname, "port": port},
        daemon=True,
    ).start()
    for _ in range(50):
        with (
            contextlib.suppress(ConnectionRefusedError, OSError),
            socket.create_connection((hostname, port), timeout=0.1),
        ):
            break
        time.sleep(0.1)
    return f"http://{hostname}:{port}"


def test_provider(app_server: str, pacts_path: Path) -> None:
    """
    Test the provider against the consumer contract.

    Runs the Pact verifier against the FastAPI provider using the contract
    generated by the consumer tests. State handlers ensure the database is
    in the correct state for each interaction.
    """
    verifier = (
        Verifier("xml-provider")
        .add_source(pacts_path)
        .add_transport(url=app_server)
        .state_handler(
            {
                "the user exists": mock_user_exists,
                "the user doesn't exist": mock_user_does_not_exist,
            },
            teardown=True,
        )
    )

    verifier.verify()


def mock_user_exists(
    action: Literal["setup", "teardown"],
    parameters: dict[str, Any],
) -> None:
    """
    Mock the provider state where a user exists.

    Args:
        action:
            Either "setup" or "teardown".
        parameters:
            Must contain "id" and optionally "name".
    """
    user = User(
        id=int(parameters.get("id", 1)),
        name=str(parameters.get("name", "Alice")),
    )

    if action == "setup":
        UserDb.create(user)
        return

    if action == "teardown":
        with contextlib.suppress(KeyError):
            UserDb.delete(user.id)
        return

    msg = f"Unknown action: {action}"
    raise ValueError(msg)


def mock_user_does_not_exist(
    action: Literal["setup", "teardown"],
    parameters: dict[str, Any],
) -> None:
    """
    Mock the provider state where a user does not exist.

    Args:
        action:
            Either "setup" or "teardown".
        parameters:
            Must contain "id".
    """
    if "id" not in parameters:
        msg = "State must contain an 'id' field to mock user non-existence"
        raise ValueError(msg)

    uid = int(parameters["id"])

    if action == "setup":
        if user := UserDb.get(uid):
            UserDb.delete(user.id)
        return

    if action == "teardown":
        return

    msg = f"Unknown action: {action}"
    raise ValueError(msg)
