name: Trigger update to docs.pact.io

on:
  push:
    branches:
      - master
    paths:
      - "**.md"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs.pact.io update workflow
        run: |
          curl -X POST https://api.github.com/repos/pact-foundation/docs.pact.io/dispatches \
                -H 'Accept: application/vnd.github.everest-preview+json' \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -d '{"event_type": "pact-python-docs-updated"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKENFORTRIGGERINGPACTDOCSUPDATE }}
